version: '3.8'

services:
  express-server:
    build:
      context: .
      dockerfile: Dockerfile  # explicit af
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - python-service

  python-service:
    build:
      context: ./python
      dockerfile: Dockerfile  # also explicit inside python folder
    ports:
      - "3030:3030"